services:
  - type: web
    name: sistema-casos-comunitarios
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput && python create_superuser.py
    startCommand: gunicorn sistema_casos_comunitario.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: sistema-cc-2025nov.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://sistema-cc-2025nov.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: casos-comunitarios-db
          property: connectionString

  - type: postgres
    name: casos-comunitarios-db
    databaseName: casos_db
    user: casos_user
    plan: free