      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: sistema-cc-2025nov.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://sistema-cc-2025nov.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: casos-comunitarios-db
          property: connectionString

  - type: postgres
    name: casos-comunitarios-db
    databaseName: casos_db
    user: casos_user
    plan: free